AppBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        authorId:
            type: integer
            column: author_id
        title:
            type: string
            length: 255
        url:
            type: string
            length: 255
            unique: true
        content:
            type: text
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    manyToOne:
        author:
            targetEntity: AppBundle\Entity\Author
            inversedBy: article
            joinColumn:
                name: author_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setCreatedAt, setUpdatedAt ]
        preUpdate: [ setUpdatedAt ]
